### ISSUE TITLE
Feature Request: Last Query Timestamp

### ISSUE THREAD

**Issue by ryanbuckner** [FlyingDiver/Indigo-BMW-CD#9]
It would be very helpful to have a custom Indigo state that indicates the last time the API request was made, whether data changed or not. It would be nice to know while testing control pages and triggers whether the update hasn't occurred yet or the query hasn't fired.

**Comment by FlyingDiver** [comment]
Added timestamp which is returned by the API and represents (I think) the time of the last update from the vehicle to the servers.  Matches what the iOS app shows (without TZ correction).
